services:
  go-links:
    build: .
    container_name: go-links
    ports:
      - "80:3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PORT=3001
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3001/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
